### ISSUE TITLE
Reference gene/genome error

### ISSUE THREAD

**Issue by congle25** [YosefLab/TRAPeS#2]
Hi thanks for making this available. I'm trying to run your tool and have the following error:
ValueError: invalid reference `NC_000080.6`

I did align my fastq file using Tophat 2 to mm10, but I'm using the one with USCS genome annotation so I wonder if this is an issue and do you have suggestions to help fix this please?

Thanks a lot!

**Comment by shakea02** [comment]
Hi,
Thank you for bringing this to my attention, apologies for the delayed response. 
The error was due to difference in the naming of the chromosomes between your aligned bam files and our annotation of the V/J/C segments supplied by TRAPeS (found under Data/mm10/mm10.TCR.bed). We were using the NCBI chromosome numbers while I assume you were using the more common naming of chr1, chr2 etc... 
I changed the chromosome names in our software to fit that convention. You can push the new version or simply download again the Data/mm10/mm10.TCR.bed file.
Let me know if you are still having problem running the software.

Best,
Shaked

**Comment by livnatje** [comment]
Hi Shaked,

Thanks for providing the code!

I'm trying to run it and get the following error. It seems to be working until the stage of writing the results to the summary file. Any idea why?

Thanks a lot,
Livnat

2016-11-30 12:19:30.017238 Finding productive CDR3
2016-11-30 12:19:35.054438 Writing results to summary file
Traceback (most recent call last):
  File "trapes.py", line 1667, in <module>
    args.singleCell, args.path, args.sumF, args.lowQ)
  File "trapes.py", line 54, in runTCRpipe
    minOverlap, rsem, bowtie2, lowQ)
  File "trapes.py", line 257, in runSingleCell
    unDictAlpha, unDictBeta, idNameDict)
  File "trapes.py", line 426, in makeSingleCellOutputFile
    writeChain(outF, 'alpha',alphaDict,alphaRsem, alphaBam, fastaDict,unDictAlpha, output, idNameDict)
  File "trapes.py", line 448, in writeChain
    rank = getRank(tcr, rsemDict, unRsemDict, isProd, noRsem)
UnboundLocalError: local variable 'rsemDict' referenced before assignment
